TWILIO_ACCOUNT_SID: AC309ecc6b635e0352480eb78de524c4ce
TWILIO_API_KEY: SK8854e119244657f21a7049000c8abdbc
TWILIO_API_SECRET: tN2FC8ydCeSGaj2VvQGc4sOc5JCCxpha

TWILIO_CHAT_SERVICE_SID: IS8aab1320365f43fbb4bd92bfd20d5318
TWILIO_SYNC_SERVICE_SID: ISdd50a1ece4cf653e900f7db1de63568f
TWILIO_NOTIFICATION_SERVICE_SID: ISb49cc6f4d6f44d663442213f5180ee2a